### ISSUE TITLE
Disable excessive logging

### ISSUE THREAD

**Issue by olcayertas** [flomio/flomio-sdk-ios#7]
I have FlojackMsr and when my application starts running the SDK logs following messages excessively:

```
sourceTimer Fired
communication:1 CommCounter: 0
Check status comm & bat
elapsedTime: 0.000000
Polling for tags
in didSendStatus
Stat Response time = 0.125901
Stat Sleep Setting = 30
Battery Level:100
timer running on <NSThread: 0x1c0462b80>{number = 5, name = (null)} thread
```
Is tehere any way to stop it?

**Comment by gormster** [comment]
It seems like Flomio release their SDKs as the DEBUG configuration… all the logging is still enabled, and sometimes these debug features can actually crash your app (see issue #5).

Why on earth would you release a compiled framework with debug logging enabled? Why is the framework doing *anything* with the app bundle's resources?

Why is there NO WAY to disable debugging features like this? Adding or removing the DEBUGLOG does nothing, because the framework is already compiled with it enabled.

**Comment by scottire** [comment]
I will be working on these issues tomorrow and will update here when I have updated the framework.

**Comment by scottire** [comment]
Excessive logging should be disabled for you now with the latest 3.0.2 release along with fixing the issue with referencing the main bundle. Apologies for these issues, let me know if you have any others.
